[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
